apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  to:
    kind: Service
    name: {{ .Values.appName }}
  port:
    targetPort: {{ .Values.servicePort }}
  tls:
    termination: {{ .Values.route.tls }}
