appName: my-backend-helm
namespace: ashiq16102002-dev

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# GitHub repository
git:
  repo: https://github.com/Ashiq-AR/devops-openshift-practice.git
  ref: main
  webhookSecret: github-webhook-secret

# Context directory within the Git repo for this chart's build (optional)
contextDir: backend

# Deployment
replicas: 2
containerPort: 8000

# Service
service:
  type: ClusterIP
  port: 82
servicePort: 82

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# HTTPRoute (gateway-api)
httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: gateway
      sectionName: http
  hostnames:
    - chart-example.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /headers

# Route
route:
  tls: edge

# If true, also create a native Kubernetes Deployment (default: false for OpenShift S2I flow)
createDeployment: false

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
