apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "..fullname" . }}-config
  namespace: {{ .Values.namespace }}
data:
  ENV_NAME: {{ .Values.env.name | quote }}
  WELCOME_MESSAGE: {{ .Values.env.welcomeMessage | quote }}
